In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("C:\\Users\\nafiz-shawon\\.cache\\kagglehub\\datasets\\kundanbedmutha\\student-performance-dataset\\versions\\1\\Student_Performance.csv")
df

,student_id,age,gender,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,study_method,math_score,science_score,english_score,overall_score,final_grade
0,1,14,male,public,post graduate,3.1,84.3,yes,<15 min,yes,notes,42.7,55.4,57.0,53.1,e
1,2,18,female,public,graduate,3.7,87.8,yes,>60 min,no,textbook,57.6,68.8,64.8,61.3,d
2,3,17,female,private,post graduate,7.9,65.5,no,<15 min,no,notes,84.8,95.0,79.2,89.6,b
3,4,16,other,public,high school,1.1,58.1,no,15-30 min,no,notes,44.4,27.5,54.7,41.6,e
4,5,16,female,public,high school,1.3,61.0,yes,30-60 min,yes,group study,8.9,32.7,30.0,25.4,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,12047,17,female,public,phd,1.8,55.2,yes,15-30 min,no,mixed,55.8,48.5,46.7,46.1,e
24996,1102,16,female,private,diploma,2.7,97.1,yes,<15 min,no,coaching,64.8,48.2,52.3,56.5,d
24997,4422,19,other,private,post graduate,1.0,63.0,yes,<15 min,no,group study,50.5,20.3,36.1,36.7,f
24998,7858,14,male,private,diploma,1.0,69.4,yes,15-30 min,yes,group study,13.0,34.2,7.3,34.1,f
24999,11621,18,other,public,no formal,0.7,60.3,yes,30-60 min,no,mixed,36.5,45.1,16.5,31.4,f

In [4]:
df.head(5)

,student_id,age,gender,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,study_method,math_score,science_score,english_score,overall_score,final_grade
0,1,14,male,public,post graduate,3.1,84.3,yes,<15 min,yes,notes,42.7,55.4,57.0,53.1,e
1,2,18,female,public,graduate,3.7,87.8,yes,>60 min,no,textbook,57.6,68.8,64.8,61.3,d
2,3,17,female,private,post graduate,7.9,65.5,no,<15 min,no,notes,84.8,95.0,79.2,89.6,b
3,4,16,other,public,high school,1.1,58.1,no,15-30 min,no,notes,44.4,27.5,54.7,41.6,e
4,5,16,female,public,high school,1.3,61.0,yes,30-60 min,yes,group study,8.9,32.7,30.0,25.4,f

In [5]:
df.tail()

,student_id,age,gender,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,study_method,math_score,science_score,english_score,overall_score,final_grade
24995,12047,17,female,public,phd,1.8,55.2,yes,15-30 min,no,mixed,55.8,48.5,46.7,46.1,e
24996,1102,16,female,private,diploma,2.7,97.1,yes,<15 min,no,coaching,64.8,48.2,52.3,56.5,d
24997,4422,19,other,private,post graduate,1.0,63.0,yes,<15 min,no,group study,50.5,20.3,36.1,36.7,f
24998,7858,14,male,private,diploma,1.0,69.4,yes,15-30 min,yes,group study,13.0,34.2,7.3,34.1,f
24999,11621,18,other,public,no formal,0.7,60.3,yes,30-60 min,no,mixed,36.5,45.1,16.5,31.4,f

In [6]:
df.columns

Index(['student_id', 'age', 'gender', 'school_type', 'parent_education',
       'study_hours', 'attendance_percentage', 'internet_access',
       'travel_time', 'extra_activities', 'study_method', 'math_score',
       'science_score', 'english_score', 'overall_score', 'final_grade'],
      dtype='object')

In [7]:
df_columns = np.array(df.columns) 
df_columns

array(['student_id', 'age', 'gender', 'school_type', 'parent_education',
       'study_hours', 'attendance_percentage', 'internet_access',
       'travel_time', 'extra_activities', 'study_method', 'math_score',
       'science_score', 'english_score', 'overall_score', 'final_grade'],
      dtype=object)

In [8]:
print(df_columns.dtype)

object

In [9]:
df.index

RangeIndex(start=0, stop=25000, step=1)

In [10]:
df.info

<bound method DataFrame.info of        student_id  age  gender school_type parent_education  study_hours  \
0               1   14    male      public    post graduate          3.1
1               2   18  female      public         graduate          3.7
2               3   17  female     private    post graduate          7.9
3               4   16   other      public      high school          1.1
4               5   16  female      public      high school          1.3
...           ...  ...     ...         ...              ...          ...
24995       12047   17  female      public              phd          1.8
24996        1102   16  female     private          diploma          2.7
24997        4422   19   other     private    post graduate          1.0
24998        7858   14    male     private          diploma          1.0
24999       11621   18   other      public        no formal          0.7

       attendance_percentage internet_access travel_time extra_activities  \
0                       84.3             yes     <15 min              yes
1                       87.8             yes     >60 min               no
2                       65.5              no     <15 min               no
3                       58.1              no   15-30 min               no
4                       61.0             yes   30-60 min              yes
...                      ...             ...         ...              ...
24995                   55.2             yes   15-30 min               no
24996                   97.1             yes     <15 min               no
24997                   63.0             yes     <15 min               no
24998                   69.4             yes   15-30 min              yes
24999                   60.3             yes   30-60 min               no

      study_method  math_score  science_score  english_score  overall_score  \
0            notes        42.7           55.4           57.0           53.1
1         textbook        57.6           68.8           64.8           61.3
2            notes        84.8           95.0           79.2           89.6
3            notes        44.4           27.5           54.7           41.6
4      group study         8.9           32.7           30.0           25.4
...            ...         ...            ...            ...            ...
24995        mixed        55.8           48.5           46.7           46.1
24996     coaching        64.8           48.2           52.3           56.5
24997  group study        50.5           20.3           36.1           36.7
24998  group study        13.0           34.2            7.3           34.1
24999        mixed        36.5           45.1           16.5           31.4

      final_grade
0               e
1               d
2               b
3               e
4               f
...           ...
24995           e
24996           d
24997           f
24998           f
24999           f

[25000 rows x 16 columns]>

In [11]:
df.sample(10)

,student_id,age,gender,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,study_method,math_score,science_score,english_score,overall_score,final_grade
19108,3199,19,male,public,no formal,5.0,82.4,yes,15-30 min,yes,notes,82.4,59.9,79.6,72.8,c
24950,3383,19,male,private,no formal,2.3,97.4,yes,>60 min,no,mixed,58.9,48.7,46.2,48.0,e
13925,13926,17,female,public,post graduate,1.8,90.8,yes,>60 min,yes,coaching,54.1,58.9,33.1,58.0,d
1779,1780,18,female,public,phd,6.8,52.1,yes,15-30 min,yes,mixed,62.1,66.9,70.3,70.1,c
24003,3202,19,male,public,high school,4.1,87.8,no,>60 min,no,mixed,84.6,69.7,62.4,70.8,c
6345,6346,18,male,private,no formal,2.2,61.2,no,30-60 min,no,online videos,38.9,33.5,33.7,39.2,f
17443,8942,19,other,public,post graduate,2.4,95.2,yes,30-60 min,yes,textbook,58.7,58.7,76.5,61.2,d
14201,14202,16,other,private,diploma,2.6,85.5,yes,<15 min,yes,online videos,45.0,55.3,57.4,46.8,e
18725,4261,15,other,public,no formal,7.2,60.7,yes,15-30 min,no,coaching,83.9,84.8,83.6,83.7,c
4247,4248,15,other,private,graduate,3.9,84.2,yes,30-60 min,no,notes,86.8,74.2,70.3,70.2,c

In [12]:
df.describe()

,student_id,age,study_hours,attendance_percentage,math_score,science_score,english_score,overall_score
count,25000.00000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000
mean,7493.04380,16.482760,4.253224,75.084084,63.785944,63.745320,63.681948,64.006172
std,4323.56215,1.703895,2.167541,14.373171,20.875262,20.970529,20.792693,18.932025
min,1.00000,14.000000,0.500000,50.000000,0.000000,0.000000,0.000000,14.500000
25%,3743.75000,15.000000,2.400000,62.800000,48.300000,48.200000,48.300000,49.000000
50%,7461.50000,16.000000,4.300000,75.100000,64.100000,64.100000,64.200000,64.200000
75%,11252.00000,18.000000,6.100000,87.500000,80.000000,80.000000,80.000000,79.000000
max,15000.00000,19.000000,8.000000,100.000000,100.000000,100.000000,100.000000,100.000000

In [13]:
my_list = [['nafiz', 23], ['mahmud', 343], ['shawon', 454]]
list_df = pd.DataFrame(my_list, columns=['name', 'age'], index=[1,2,3])
list_df

     name  age
1   nafiz   23
2  mahmud  343
3  shawon  454

In [14]:
print(type(list_df))

<class 'pandas.core.frame.DataFrame'>

In [15]:
my_tuple = (('nafiz', 23), ('mahmud', 343), ('shawon', 454))
tuple_df = pd.DataFrame(my_tuple, columns=['name', 'age'], index=[1,2,3])
tuple_df

     name  age
1   nafiz   23
2  mahmud  343
3  shawon  454

In [16]:
my_dict = {
    'Name': ['nafiz', 'mahmud', 'shawon'],
    'Ago': [23,34,45],
    'dummy': [34,45,65]
}
dict_df = pd.DataFrame(my_dict)
dict_df

     Name  Ago  dummy
0   nafiz   23     34
1  mahmud   34     45
2  shawon   45     65

In [17]:
my_dict = [
    {'Name': 'nafiz', 'age': 34, 'blood': 'o'},
    {'Name': 'mahmud', 'age': 44, 'blood': 'b'},
    {'Name': 'shawon', 'age': 54, 'blood': 'o-'}
    
]
dict_df = pd.DataFrame(my_dict)
dict_df

     Name  age blood
0   nafiz   34     o
1  mahmud   44     b
2  shawon   54    o-

In [18]:
print(type(dict_df['Name']))

<class 'pandas.core.series.Series'>

In [19]:
df

,student_id,age,gender,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,study_method,math_score,science_score,english_score,overall_score,final_grade
0,1,14,male,public,post graduate,3.1,84.3,yes,<15 min,yes,notes,42.7,55.4,57.0,53.1,e
1,2,18,female,public,graduate,3.7,87.8,yes,>60 min,no,textbook,57.6,68.8,64.8,61.3,d
2,3,17,female,private,post graduate,7.9,65.5,no,<15 min,no,notes,84.8,95.0,79.2,89.6,b
3,4,16,other,public,high school,1.1,58.1,no,15-30 min,no,notes,44.4,27.5,54.7,41.6,e
4,5,16,female,public,high school,1.3,61.0,yes,30-60 min,yes,group study,8.9,32.7,30.0,25.4,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,12047,17,female,public,phd,1.8,55.2,yes,15-30 min,no,mixed,55.8,48.5,46.7,46.1,e
24996,1102,16,female,private,diploma,2.7,97.1,yes,<15 min,no,coaching,64.8,48.2,52.3,56.5,d
24997,4422,19,other,private,post graduate,1.0,63.0,yes,<15 min,no,group study,50.5,20.3,36.1,36.7,f
24998,7858,14,male,private,diploma,1.0,69.4,yes,15-30 min,yes,group study,13.0,34.2,7.3,34.1,f
24999,11621,18,other,public,no formal,0.7,60.3,yes,30-60 min,no,mixed,36.5,45.1,16.5,31.4,f

In [20]:
df['school_type']

0         public
1         public
2        private
3         public
4         public
          ...
24995     public
24996    private
24997    private
24998    private
24999     public
Name: school_type, Length: 25000, dtype: object

In [21]:
type(df['school_type'])

pandas.core.series.Series

In [27]:
df.loc[1]

student_id                      2
age                            18
gender                     female
school_type                public
parent_education         graduate
study_hours                   3.7
attendance_percentage        87.8
internet_access               yes
travel_time               >60 min
extra_activities               no
study_method             textbook
math_score                   57.6
science_score                68.8
english_score                64.8
overall_score                61.3
final_grade                     d
Name: 1, dtype: object

In [25]:
df

,student_id,age,gender,school_type,parent_education,study_hours,attendance_percentage,internet_access,travel_time,extra_activities,study_method,math_score,science_score,english_score,overall_score,final_grade
0,1,14,male,public,post graduate,3.1,84.3,yes,<15 min,yes,notes,42.7,55.4,57.0,53.1,e
1,2,18,female,public,graduate,3.7,87.8,yes,>60 min,no,textbook,57.6,68.8,64.8,61.3,d
2,3,17,female,private,post graduate,7.9,65.5,no,<15 min,no,notes,84.8,95.0,79.2,89.6,b
3,4,16,other,public,high school,1.1,58.1,no,15-30 min,no,notes,44.4,27.5,54.7,41.6,e
4,5,16,female,public,high school,1.3,61.0,yes,30-60 min,yes,group study,8.9,32.7,30.0,25.4,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,12047,17,female,public,phd,1.8,55.2,yes,15-30 min,no,mixed,55.8,48.5,46.7,46.1,e
24996,1102,16,female,private,diploma,2.7,97.1,yes,<15 min,no,coaching,64.8,48.2,52.3,56.5,d
24997,4422,19,other,private,post graduate,1.0,63.0,yes,<15 min,no,group study,50.5,20.3,36.1,36.7,f
24998,7858,14,male,private,diploma,1.0,69.4,yes,15-30 min,yes,group study,13.0,34.2,7.3,34.1,f
24999,11621,18,other,public,no formal,0.7,60.3,yes,30-60 min,no,mixed,36.5,45.1,16.5,31.4,f

In [26]:
type(df.loc[0])

pandas.core.series.Series